### ISSUE TITLE
Infinite Scroll

### ISSUE THREAD

**Issue by willianjusten** [free-time/free-time.github.io#10]
Hoje a página já tem muita coisa e tende a crescer ainda mais. Para que o site abra rápido e a interação seja melhor, seria bom aplicarmos um infinite scroll, carregando sob demanda, isso facilitará muito a performance do site.

Aqui uns links para olharmos depois:

http://blog.scottlogic.com/2014/10/14/jekyll-pagination-and-infinite-scrolling.html
https://github.com/tobiasahlin/infinite-jekyll
https://github.com/infinite-scroll/infinite-scroll (Esse último já está deprecated, mas é bom ver a técnica)

**Comment by fdaciuk** [comment]
Fiz um a um tempo atrás: https://github.com/fdaciuk/js-components/blob/master/modules/InfiniteScroll.js
A doc dele está aqui: https://github.com/fdaciuk/js-components/wiki/Infinite-Scroll

Depende de jQuery xD

**Comment by bukinoshita** [comment]
Daora, vou testar! Valeu @fdaciuk :smile:

**Comment by willianjusten** [comment]
O Rafael Amorim fez um também, sem o jQuery de dependência, também vale olhar.

https://github.com/raphamorim/inphinity
