### ISSUE TITLE
Implementar uma busca

### ISSUE THREAD

**Issue by willianjusten** [free-time/free-time.github.io#11]
Podemos implementar uma busca básica, aos mesmos moldes que eu fiz/faço no meu blog. Trabalhando com a criação de um JSON base com todos os dados.

https://github.com/willianjusten/willianjusten.github.io/blob/master/search.json

**Comment by andersoonweb** [comment]
@willianjusten já tenho uma busca dentro do código, ela está comentada.
Olhando seu código, não entendi muito... Falta de experiência! 
No exemplo do free-time, temo um lupa que quando clicar nela deverá filtrar a informação preenchida no campo.
Mas como fazer isso ? Tenho que passar que link pra isso ? 
Gratidão.

**Comment by willianjusten** [comment]
Opa @andersonweb, o objetivo é criar um json no momento de compilação do jekyll, contendo todas as palestras. Depois fica fácil fazer um fuzzy search a partir do JSON e retornar o link para quem estiver buscando =)

Assim que eu implementar, te mostro e explico como faz.

**Comment by andersoonweb** [comment]
Show!! na espera @willianjusten
