### ISSUE TITLE
Offline + Notification

### ISSUE THREAD

**Issue by thulioph** [free-time/free-time.github.io#119]
Passei um tempo com a aba aberta, porém inativa, quando voltei tinha conteúdo novo e só descobri depois de um **F5**. O que acham de adicionar o `.appcache` pra gerenciar conteúdo offline e pra cada novidade, mandar uma notificação informando? No futuro podemos usar `service worker` já que o Github possui **https**.

Esse insight vem do [devdocs.io](http://devdocs.io) que possui suporte offline e quando tem novidade ele manda notificação e instruções pra atualizar o conteúdo.

:smile:

**Comment by andersoonweb** [comment]
Muito boa a ideia @thulioph !

Vou dar uma lida sobre o assunto.
Se quiser implementar... A vontade!

**Comment by thulioph** [comment]
Ja é @andersonweb mando um pr a noite quando chegar em casa ;)

**Comment by andersoonweb** [comment]
Boa @thulioph :smile:

**Comment by thulioph** [comment]
Iniciei mas depois mando um pr quando finalizar, terminei levando pau com o Jekyll :disappointed: 

> [implementação parcial aqui](https://github.com/thulioph/free-time.github.io/tree/offline-notifications)

**Comment by andersoonweb** [comment]
Boa @thulioph ! Estou a procura de um tempo pra puder ler um pouco e tentar ajudar.

**Comment by eduardojmatos** [comment]
@thulioph @andersoonweb galere, desaconselho usarem AppCache. Logo os browsers vão remover essa feature em favor do Service Workers (que faz cache de arquivos também, mas via worker de JS)

**Comment by thulioph** [comment]
@eduardojmatos pode crer, eu tinha feito essa proposta quando não sabia muito de Service Worker :)
