### ISSUE TITLE
Video privado

### ISSUE THREAD

**Issue by walternascimentobarroso** [free-time/free-time.github.io#140]
Olá pessoal,

O vídeo de titulo **A Linguagem do google GoLang** feito **Por: Bruno Costa** esta dando como vídeo privado, não consigo assistir, alguém consegue?

https://www.youtube.com/watch?v=brReIBG-7m8

**Comment by andersoonweb** [comment]
@walternascimentobarroso também não conseguir acessar, diz que estar privado.
Sempre rola dessas, :cry: .
Vamos tentar entrar em contato com o Palestrante ?

**Comment by walternascimentobarroso** [comment]
@andersoonweb encontrei esse video
https://www.youtube.com/watch?v=Qr3DPJugoMo
mesmo titulo e mesmo autor

troco so a url e mando o comite?
ou tento entrar em contato com dono da palestra e ver esse video bloqueado?

**Comment by andersoonweb** [comment]
Troca URL mesmo @walternascimentobarroso :)

PS: Por causa desses e outros problemas estou a estudar a API do Youtube, e outras tecnologias, para que possamos implementar fetures melhores, como:
- Se o vídeo estiver privado ou com passar do tempo, ele ficou privado, não ser apresentado.
  -  Ordem de publicação, ou seja,  os vídeos serão arrumados com suas datas "originais" - Nem tão originais assim, de acordo foram postado no Youtube. 
  - E outras. :dancer: 

Se você, e outras pessoas tiverem interessado em participar do processo, vamos conversar mais :smiley:

**Comment by walternascimentobarroso** [comment]
@andersoonweb legal ;)

**Comment by walternascimentobarroso** [comment]
@andersoonweb link com a correção enviado, vou fechar a issue
