### ISSUE TITLE
Videos do luiz gonzaga não estão disponiveis

### ISSUE THREAD

**Issue by walternascimentobarroso** [free-time/free-time.github.io#143]
tem duas palestras do luiz gonzaga dos santos filho que não estão disponiveis,
uma é **Desenvolvendo Peopleware** https://www.youtube.com/watch?v=X3ejbe-DfAc
e a outra é **Aplicações 12 Fatores** https://www.youtube.com/watch?v=pPO13av5jsM

tentei encontrar outros links, mas não achei, alguem sabe de algum outro link? ou vamos remover?

**Comment by andersoonweb** [comment]
@walternascimentobarroso é melhor retirar... 

Bom, vou te por na organização, pode ser? Visto que, está colaborando sempre com o projeto :smile: .

**Comment by walternascimentobarroso** [comment]
legal :heart: ,

mas tarde envio o comite removendo eles

**Comment by andersoonweb** [comment]
Tudo bem @walternascimentobarroso ! Convite enviado; xD

**Comment by walternascimentobarroso** [comment]
fixed up ;)
