### ISSUE TITLE
Versão 2.0 Free time 

### ISSUE THREAD

**Issue by andersoonweb** [free-time/free-time.github.io#148]
Pessoal. Venho a um bom tempo pensando em dar uma nova cara ao free time. Tanto em desenvolver um layout mais bonito, quanto melhorar sua performance - fechar algumas issues muito importantes.
Essa melhoria vinha sendo interrompida, pois, não conseguia achar alguém que fizesse um layout. Bom, investir, estudei um pouco, e eu mesmo venho trazendo um resultado, layout de como será a nova versão do free time. E desta vez, com bastante features legais.  Algumas será citada abaixo:
- Apresentar uma newsletters, surgerida na issue #45  
- Implementação da dica sugerida pelo @lagden na issue #47
- Uma das mais importantes, a partir da issue #59, me fez pensar uma forma de melhorar a forma de como a imagem do palestrante é exibida. Visto que, temos um resultado satisfatório, mas não muito legal. Pensei em exibirmos o thumbnail do próprio vídeo, utilizando a API do Youtube. Visto que, só extraímos apresentações de lá. Adotando essa feature, por consequência vamos ter uma grande performace quando fomos adicionar palestras. Visto que é um pouco massante da forma atual (procurar a imagem, salvar dentro da pasta, renomear, copiar o nome e publicar no CLI. Se você não entendeu nada, dá uma olhadinha [nisso](https://github.com/free-time/freetime-cli). É a ferramenta que registra as publicações).
- Integração de perfil para palestrantes. Onde irá conter todas todas suas talks e uma breve apresentação sobre o mesmo.
- Adicionar Offline + Notification, como foi citada na issue #119 
- Adicionar tempo de cada palestra, sugerido na issue, #147, Podemos pegar diretamente do Youtube.
- Organizar com as datas que foram publicada no Youtube.  
-  Adicionar talks em outras linguagem também. Em especial, English.  

Abaixo, vou apresentar a vocês o layout que fiz. Estou na espera de qualquer feedback de vocês. Para que possamos criar um projeto bem estável.

> Falta bastante coisa. Porém, acredito que já temos uma noção de como será feito!

![intro](https://cloud.githubusercontent.com/assets/3930770/19628080/a47ac31c-9934-11e6-9dc3-7efd3f77b2b5.jpg)

![interna](https://cloud.githubusercontent.com/assets/3930770/19628095/f4c60228-9934-11e6-8de7-e275afc1aadc.jpg)

Ah, sem esquecer a stack que pretendo utilizar:
- HTML/CSS
- Jekyll
- React
- API Youtube
- Firebase (quem sabe vamos fazer um sistema de login)
- Algo que faça o Offiline, por enquanto ainda não sei.

Acho que é isso o que pretendo utilizar. Ficaria bem feliz se houvesse a opinião de vocês, o que acha da stack? O que pode ser incluído, o que deve ser retirado. Comente, nós ajude! \o/

@lfilho @michelamaral @fdaciuk @rafaelstz @dodops @raphamorim @emanuelgsouza @walternascimentobarroso @willianjusten @BuKinoshita @IAMFELIPEMATTOS @gfkauer @afonsopacifer @thulioph @neysimoes @theandersonn @twobanks @realronchi @lucasmaiaesilva @icarcal @horochovec @eduardojmatos @filipelinhares @diessica @vicainelli @mauriciojunior @humrochagf @dodops

**Comment by fdaciuk** [comment]
Legal cara, parabéns pela iniciativa =)
Acho que pode ser interessante também deixar um vídeo aleatório de fundo.. pode ser um random mesmo dos vídeos que estarão na lista, em baixa qualidade para não pesar xD

**Comment by emanuelgsouza** [comment]
Fenomenal! Mais do que aprovado

**Comment by afonsopacifer** [comment]
Muito bom mano... 
Acho valido organizar essas sugestões que surgiram nas issues e tal.. e botar para frente, acho que pode ficar muito massa mesmo..

**Minhas considerações sobre a Stack:**
- **Jekyll** é legal para gerar as paginas, e tem o lance do Build e talz... ok.. todo mundo sabe..
- **React** não sei.. acho que vamos acabar falando de SEO sei la.. e vamos acabar caindo no lance de server render e tal.. e vai dar merda.. acho que não tem necessidade de usar React para renderizar uma lista de videos e um pagina para exibir um video que vem direto do **youtube** pela API.
- **Firebase** é lindo, mas não se é preciso fazer algo com login, até pq nossos "users" serão Devs, e podem entrar no **github** e mandar um PR com algum conteúdo novo.. logo acho que não precisa dessa feature na versão 2.. talvez em uma 2.1 saka.
- Para rodar **Offline**, dá para usar **Service Workers** para cachear os assets e linkar um **APP Cache** como fallback para ficar progressivo ;)

**Minhas considerações sobre o Layout:**

Eu acho que uma dica seria esquecer a questão **visual**... foca na **usabilidade da interface**. beleza é relativa.. o que importante é tem uma boa usabilidade o que implica em uma boa **UX**. De qualquer forma não dá para acertar de cara.. com o tempo vamos ter que ajustar a interface mesmo.. então relaxa.

Esquece photoshop e essas coisas... o tempo de criar algo ali.. vc tem 10 ideias  **direto no papel**.. RELAXA.. visual é o d menos.. um boa interface precisa ser simples e **minimalista**, mas principalmente com uma boa usabilidade.

Depois de ter um **wireframe** legal.. e entendermos + ou - o que será a interface, podemos fazer um **prototipo com HTML + CSS**, e a partir disso ajustar a parte visual.. nesse ponto algum **designer de UI** já deve ter se apresentado para pensar em algo lindão.

**Comment by andersoonweb** [comment]
@fdaciuk Onde seria essa implementação? Na página de "introdução" ?

**Comment by andersoonweb** [comment]
Muito bom @afonsopacifer. 
Em relação ao React, vou utilizar ele por questão de aprendizado. Mas vou rever isso ae. Pesquisar um pouco e te retorno!

Sobre o Firebase, concordo. talvez em uma versão 2.1 seria o ideal! 
Em relação ao designer e ao layout. Eu estou meio que estudando essa área de designer e tals. Então, pra mim isso é como estar brincando e ao mesmo tempo praticando, tá sendo uma experiência muito bacana. Essa ideologia pra me, no momento não se encaixa. A ideia é "_perder tempo_" e extrair o máximo de conhecimento que puder. Concordo que temos muito que melhorar e ajustar muitas coisas ainda.

Ah... Sobre o offiline, acabei pesquisando e estava pensando em utilizar o **Service Workers** mesmo.
Valeu demais por tá opinando. São dicas bem valiosas.

**Comment by theandersonn** [comment]
Cara sabe que eu utilizo Free Time regularmente :punch:
As modificações listadas deixarão o site um agregador/repositório de vídeos muito massa. 

Sim, a forma de contribuir está um pouco massante, a simplificação do processo é válido.

O que acha da home ter a exibição dos vídeos mais acessados? ao invés de uma tela com background somente.

Acho que Jekyll está atendendo bem, o lance que deixa burocrático e a inclusão da thumb. React não sei se realmente é preciso.

Quanto ao layout porque não abre uma issue no Front-End BR pra ver se algum design contribui com um layout?

**Comment by eduardojmatos** [comment]
@andersoonweb muito bacana cara! A versão 2.0 vai arrebentar!

Se precisar de ajuda de layout, talvez o @diogorodrigues pode ajudar na interface - mencionei aqui pra só ver se ele tem tempo e se você precisar também. Ele quem fez o site de eventos do Frontendbr 😄 

Sobre offline, se precisar de help eu posso ajudar! A dica do @afonsopacifer de criar as issues aqui é bem boa, porque cada um pode ajudar em algo específico!

Parabéns pelo projeto!!!

**Comment by vicainelli** [comment]
Referência de interface: [YouTube Gaming](https://gaming.youtube.com/)

![screen shot 2016-10-24 at 12 03 37](https://cloud.githubusercontent.com/assets/1155694/19648778/08f16712-99e2-11e6-8aea-82bbd93d7a2a.png)

**Comment by rafaelstz** [comment]
@andersoonweb muito bom! :+1: :smile: :tada:

**Comment by walternascimentobarroso** [comment]
@andersoonweb vai ficar otimo <3

**Comment by twobanks** [comment]
@andersoonweb essa versão 2.0 promete!

Parabéns pelo projeto!!!! 👍👍👍

**Comment by erickpatrick** [comment]
Recomendo [dar uma olhada nesse tutorial](https://webdesign.tutsplus.com/tutorials/how-to-lazy-load-embedded-youtube-videos--cms-26743) (tem a [versão em pt-br](https://webdesign.tutsplus.com/pt/tutorials/how-to-lazy-load-embedded-youtube-videos--cms-26743) dele), explicando uma técnica de como carregar os vídeos do YouTube sob demanda. Com certeza vai ajudar bastante na performance da página.

**Comment by andersoonweb** [comment]
Wow @erickpatrick , muito obrigado, vou conferir sim e te retornar se possível ;)
