### ISSUE TITLE
Palestra dupla

### ISSUE THREAD

**Issue by brunopulis** [free-time/free-time.github.io#24]
Pessoal, 

Estou querendo submeter uma talk pra contribuir com o projeto, porém essa talk em especifíco são dois palestrantes. 

Já pensaram em uma forma, caso seja uma palestra de duas pessoas para  inserir a foto?

**Comment by andersoonweb** [comment]
opa @brunopulis , tudo bem ? 
Primeiramente obrigado pelo contato e sua contribuição.
Assim, quando tem dois palestrantes coloca a foto apenas de um, rs... Mas no título passe o nome dos dois.
Valeu pelo contato @brunopulis , ainda alguma duvida ? fico a disposição.

**Comment by brunopulis** [comment]
@andersonweb Show :+1:
