### ISSUE TITLE
Slack para Freetime

### ISSUE THREAD

**Issue by rafaelstz** [free-time/free-time.github.io#31]
Seria legal ter um Slack ou Gitter para trocarmos idéias sobre melhorias e dividir tarefas. O que acham?

**Comment by andersoonweb** [comment]
Achei a ideia muito bacana, já tinha pensado nisso... O que acha, @BrunoKinoshita @willianjusten @Lucaslimay

**Comment by bukinoshita** [comment]
Baah, pra mim é ruim. Já to em alguns grupos e geralmente nunca olho porque tem muita mensagem. Só olho do trampo mesmo. Eu prefiro no Github mesmo, porque chega e-mail tranquilo pra mim.

Ps: Como são poucas pessoas no grupo, pode funcionar. :+1:

**Comment by andersoonweb** [comment]
Bruno está correto, o slack eu também deixo um pouco de priorizar, uso uma vez ou outra... Poderíamos ter uma page do que ainda tem que ser feito e discutir sobre a divisão de tarefas, por aqui, ou marca um hagount ao fim de semanas.

**Comment by willianjusten** [comment]
Fala galera, eu infelizmente ando muito apertado na globo.com e estou sem condições de ajudar por enquanto...=/

De qualquer forma, acho melhor que os assuntos sejam por aqui, visto que facilita para qualquer um, olhar e ajudar.
