### ISSUE TITLE
Erro ao instalar as dependências

### ISSUE THREAD

**Issue by daniloagostinho** [free-time/free-time.github.io#41]
@andersonweb , esta gerando o seguinte erro quando vou instalar as dependências do projeto. 

Passos feitos até o momento do erro:

1 - Clonei meu próprio fork.
2 - Entrei na pasta do projeto e rodei: npm i

É estranho isso acontecer porque, tenho todos os pré-requisitos instalados.

![captura de tela de 2015-11-01 22-59-16](https://cloud.githubusercontent.com/assets/13303320/10874119/9b550c4a-80ec-11e5-8dea-abc12a80a441.png)

**Comment by willianjusten** [comment]
@DaniloAgostinho, verifica por favor se existe um arquivo `package.json` na pasta que você tentou rodar o comando?

E de qualquer forma, sempre rode `sudo npm install` ao invés de somente o `i`...

**Comment by daniloagostinho** [comment]
@willianjusten De fato não existe este arquivo! Devo criá-lo?

**Comment by bukinoshita** [comment]
Cria o `package.json` assim:

```
{
  "name": "free-time",
  "version": "1.0.0",
  "description": "Use your free time to watch lectures",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/free-time/free-time.github.io.git"
  },
  "keywords": [
    "talks",
    "lectures",
    "speakers"
  ],
  "author": "Anderson Menezes",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/free-time/free-time.github.io/issues"
  },
  "homepage": "https://github.com/free-time/free-time.github.io",
  "devDependencies": {
    "browser-sync": "^1.9.0",
    "gulp": "^3.9.0",
    "gulp-concat": "^2.6.0",
    "gulp-imagemin": "^2.3.0",
    "gulp-notify": "^2.2.0",
    "gulp-plumber": "^0.6.6",
    "gulp-sass": "^2.0.4",
    "gulp-uglify": "^1.4.2"
  }
}
```

Depois da um `npm install`

**Comment by daniloagostinho** [comment]
@BuKinoshita boa! Fiz como me disse e deu certo até um certo ponto, outro gerou esse erro que acredito ser "versão incompatível do node".

Vê só:

![captura de tela de 2015-11-02 08-24-57](https://cloud.githubusercontent.com/assets/13303320/10882775/86a73daa-813b-11e5-87b7-bec4352c1dd0.png)

**Comment by bukinoshita** [comment]
Que versão de node você ta usando?

**Comment by daniloagostinho** [comment]
v0.10.25

**Comment by bukinoshita** [comment]
Você ta usando Debian?

**Comment by daniloagostinho** [comment]
Não! instalei uma versão para Debian?

**Comment by bukinoshita** [comment]
Acho que não, mas achei que era esse o problema: http://stackoverflow.com/questions/21168141/can-not-install-packages-using-node-package-manager-in-ubuntu

**Comment by bukinoshita** [comment]
Ou pode ser porque seu node ta desatualizado.

**Comment by daniloagostinho** [comment]
Vou verificar o que tá acontecendo! Agradeço.

**Comment by willianjusten** [comment]
A primeira coisa a se fazer na real mesmo é atualizar o seu repositório de acordo com o repositório original, pois se não tinha o package.json, com certeza ele está muito desatualizado...

**Comment by andersoonweb** [comment]
Realmente, ele estava com a versão do projeto antigo... 
Fez um [upstream](http://blog.da2k.com.br/2014/01/19/manter-repositorio-github-forkado-sincronizado-com-o-original/) e tudo ficou numa boa.

**Comment by daniloagostinho** [comment]
@andersonweb Agradecido! ;)
