### ISSUE TITLE
Melhorar filtro

### ISSUE THREAD

**Issue by danilovaz** [free-time/free-time.github.io#42]
Acho que se tivesse um filtro no estilo do GIF abaixo, ficaria com uma interação melhor além de possibilitar filtrar não apenas por categoria, mas também por palestrantes.

![to4vk](https://cloud.githubusercontent.com/assets/1218337/10974419/2f964cd2-83c9-11e5-8e46-65beda0b1530.gif)

**Comment by willianjusten** [comment]
Acho a ideia deveras interessante, inclusive tem plugins que facilitam isso como o [Isotope](http://isotope.metafizzy.co/layout-modes/masonry.html), mas precisa de braço para fazer também.

Porque seria uma mudança de alguns paradigmas, até mesmo porque hoje o sistema é gerado estático (jekyll) e para fazer isso que você aconselha, precisaríamos dinamizar alguns dados ou então passar tudo de uma vez só e fazer o JS trabalhar...

**Comment by andersoonweb** [comment]
boa dica @danilovaz ! mas foi como o @willianjusten citou, fica meio complicado implementar agora. podemos pensar nessa implementação numa próxima versão, fechou ?!

Thank you through the tips!
