### ISSUE TITLE
Tonar mais fácil se inscrever

### ISSUE THREAD

**Issue by andersoonweb** [free-time/free-time.github.io#44]
Atualmente, o telespectador precisa passar o e-mail duas vezes para consegui receber mensalmente palestras no seu e-mail.

**Comment by andersoonweb** [comment]
@fdaciuk você começou a fazer esse processo ? :dancer:

**Comment by fdaciuk** [comment]
Ainda não.. acho que consigo pegar daqui uns 15 dias.

**Comment by andersoonweb** [comment]
:+1:
