### ISSUE TITLE
Retirar rodapé

### ISSUE THREAD

**Issue by andersoonweb** [free-time/free-time.github.io#45]
Infinite scroll e rodapé não pega muito bem! O ideal seria remover o rodapé e adicionar uma área pra se inscrever no HEADER.
@BuKinoshita

**Comment by bukinoshita** [comment]
:+1:

**Comment by maclovin** [comment]
Complementando: Quando terminar o scroll, apresentar um rodapé simples com o minimo de informação relevante e um botão "back to top" seria interessante.

**Comment by ghost** [comment]
Também acho válido adicionar um rodapé simples com um botão para voltar ao topo.

**Comment by luisfmsouza** [comment]
Só pra movimentar a issue... tava pensando em como poderia ser a área de inscrição na home. O que acham:

![subscribe_closed](https://cloud.githubusercontent.com/assets/4405147/12425186/b96f7c86-beba-11e5-9d41-7d46c231a83b.png)

Após clicar em assinar:
![subscribe_open](https://cloud.githubusercontent.com/assets/4405147/12425187/b9767ac2-beba-11e5-8342-8bc834945094.png)

**Comment by andersoonweb** [comment]
Boa ideia! xD por mim, tudo bem...

**Comment by luisfmsouza** [comment]
Boa! Vou elaborar e começar a desenvolver.

Vou postando screeshots aqui...

**Comment by fdaciuk** [comment]
+1 pra segunda opção do @luisfmsouza :)

**Comment by andersoonweb** [comment]
Sho2 @luisfmsouza

**Comment by lucasbento** [comment]
@luisfmsouza +1, senti falta de um conteúdo nessa parte e esse parece ser ideal.
