### ISSUE TITLE
Algumas idéias extra

### ISSUE THREAD

**Issue by lagden** [free-time/free-time.github.io#47]
- [ ] Separar por categoria ou colocar um filtro
- [ ] Colocar palestra, workshop, etc... da gringa também

Workshop P2P https://opbeat.com/blog/posts/how-to-write-a-p2p-chat-application-by-mathias-buus

**Comment by andersoonweb** [comment]
Valeu @lagden!
A segunda opção já está quase certa.

**Comment by lcezermf** [comment]
Opção do Filtro é válida, ou na página inicial listar as 10 recentemente adicionadas também seria uma boa

**Comment by icaromh** [comment]
:+1: pra um filtro
