### ISSUE TITLE
Awesome!

### ISSUE THREAD

**Issue by vinicius73** [free-time/free-time.github.io#48]
Essa issue é só para dizer o quão incrível é esse repo!!!
Coloquei já ele no projeto que participo! http://awesome-br.com/ por que acho totalmente relevante ter esta lista junto a nossa!
Mais uma vez parabéns, e em breve acionarei algumas palestras :wink:

**Comment by andersoonweb** [comment]
Oi, @vinicius73 ! Valeu pela moral cara! 
Estamos contato com sua contribuição. Grande abraços
