### ISSUE TITLE
Add reponsive

### ISSUE THREAD

**Issue by andersoonweb** [free-time/free-time.github.io#5]

**Comment by ghost** [comment]
Você precisa de ideias para responsive?

**Comment by andersoonweb** [comment]
@DaniloAgostinho, pode expor suas ideias. Ele está sendo desenvolvido por @willianjusten. Toda contribuição é bem vinda!

**Comment by willianjusten** [comment]
Opa @DaniloAgostinho, por enquanto eu só fiz um trabalho de otimização, ainda vou reestruturar um pouquinho o visual e adicionar algumas novas features. Mas o objetivo é não mudar muito do que já existe, visto que o @andersonweb tem bastante carinho pelo projeto e ele já é bem legal.

**Comment by andersoonweb** [comment]
Nada @willianjusten , confio em você!

**Comment by ghost** [comment]
@willianjusten fecho!  Dei um fork no projeto vou ver se sei/posso ajudar em algo. ;)

**Comment by ghost** [comment]
Fiz alguns ajuste para o responsivo em meu fork, se alguém quiser ajudar para ter uma solução bem elaborada.

**Comment by andersonweb** [comment]
:+1: @Lucaslimay

**Comment by ghost** [comment]
@Lucaslimay vou dar uma analisada, ;)

**Comment by andersoonweb** [comment]
Done!
