### ISSUE TITLE
Informar que a mensagem do commit deve ser em inglês

### ISSUE THREAD

**Issue by luisfmsouza** [free-time/free-time.github.io#53]
Colocar a informação no CONTRIBUTING.md.

Sugestão:

Após realizar as alterações, é hora de fazer um commit com uma mensagem **em inglês** coerente do que foi feito. Exemplo:

```
git add --all
git commit -am ‘Adding a new task’
git push origin nomeDaTarefa
```

**Comment by luisfmsouza** [comment]
O que você acha @andersonweb ?

**Comment by andersoonweb** [comment]
perfeito @luisfmsouza ! Só implementar.
PS: ficaria legal também se colocasse

> Todos os commit de ser escrito em inglês

**Comment by luisfmsouza** [comment]
Boa! Amanhã eu mando uma PR.

On Tuesday, 8 December 2015, Anderson Menezes notifications@github.com
wrote:

> perfeito @luisfmsouza https://github.com/luisfmsouza ! Só implementar.
> PS: ficaria legal também se colocasse
> 
> Todos os commit de ser escrito em inglês
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/free-time/free-time.github.io/issues/53#issuecomment-163023376
> .

## 

Att,

_Luís Felipe Souza_

**Comment by andersoonweb** [comment]
fechado! :)
