### ISSUE TITLE
Padrão para fotos e direção de arte

### ISSUE THREAD

**Issue by afonsopacifer** [free-time/free-time.github.io#59]
Amigos,

Como algumas fotos ficam com a cabeça cortada, eu pensei em algo para ajudar:

Bem, minha sugestão:

Criar um padrão de tamanho para as fotos, eu vi que a altura é fixa em 125px e a largura varia chegando até + ou - 388px, acho que podemos a partir daí criar uma padrão, e editar as fotos para o formato definido, assim podemos definir melhor onde cortar e tentar ao máximo centralizar a cabeça das pessoas (rss).

Eu fiz alguns testes aqui usando o tamanho de 388 X 125 e ficou muito dificil, mesmo editando, como o tamanho fica muito retangular é complicado recortar as fotos sem cortar a cabeça, a única solução que pensei foi aumentar um pouco a altura fixa para que fique um pouco mais "quadrada" e menos retangular.

Acho que uma hora essas fotos vão acabar de chegar, ou ao menos diminuir bastante a quantidade de fotos novas entrando,logo  não existe a necessidade de pensar em como automatizar esse corte e talz, acho que é um esforço imenso não tão necessário. Ah claro, como eu to dando a ideia eu me proponho a editar tudo isso, claro :)

Ultima coisa: Podemos aproveitar essa mexida geral para apagar algumas fotos repetidas e ajustar algumas extensões de `.jpeg` > `.jpg` e outras coisinhas que estão perdidas na pasta speakers.

Enfim, o que vocês acham?
Já tinham pensado em algo para solucionar isso?

**Comment by andersoonweb** [comment]
@afonsopacifer acho bastante valida, já tinha pensando nisso há tempos, inclusive em trocar todas extensões pra .jgp ou .png, de preferência png.

Em relação ao lance de "retirar a cabeça cortadas", acho bem válido, uma boa ideia. Poderiamos chegar em um acordo, ou em um medida adequada pra que não chega a haver mais esse problema. Qual tamanho você sugere ?

Uma outra coisa é, na compilação do gulp, executamos uma task para que, deixa todas as imagens no mesmo tamanho, não tenho certeza, mas isso pode impactar na performance.

PS: vou resolver o problemas das imagens duplicadas já. #61

**Comment by andersoonweb** [comment]
Um desses problemas já foi resolvido no PR #113. Que foi deixar todas imagens com caixa baixa. Assim padronizando e dando uma facilidade na hora de publicar.
