### ISSUE TITLE
Background de link nas categorias está menor que o texto

### ISSUE THREAD

**Issue by lcezermf** [free-time/free-time.github.io#65]
Ao passar sobre um item do menu, no evento `hover` o background azul escuro está menor que o texto, no exemplo o link `Produtividade`.

Acessando no Linux/Firefox 43.0, resolução 1366x768 (16:9)

![bug](https://cloud.githubusercontent.com/assets/2160392/11969015/dd37e46c-a8fa-11e5-9eeb-29dbf3c0a027.png)

**Comment by luisfmsouza** [comment]
Uma sugestão pra resolver paliativamente é alterar o padding lateral do <a> de 20px pra 10px.

**Comment by andersoonweb** [comment]
Boa diga @luisfmsouza! Apliquei espero que dê certo em outros sistemas, aqui tá tranquilão!!! Dá um feedback, @lccezinha

**Comment by lcezermf** [comment]
Opa boa @andersonweb, mas da uma olhada aqui como está:

![free time - palestras para desenvolvedores 2015-12-27 21-21-02](https://cloud.githubusercontent.com/assets/2160392/12012521/e7190b6c-acdf-11e5-951e-f9d2ae036d38.png)

**Comment by andersoonweb** [comment]
bom, vamos p tentativa e error... Poderia mandar o print como está agora ? Valeu pela paciência :dancer:

**Comment by luisfmsouza** [comment]
@lccezinha qual sua resolução e browser?

Vou tentar reproduzir aqui pra ajudar

**Comment by luisfmsouza** [comment]
Acho que agora foi! Vamos aguardar o feedback do @lccezinha

**Comment by lcezermf** [comment]
Agora ficou show!

![free time - palestras para desenvolvedores 2015-12-28 19-33-11](https://cloud.githubusercontent.com/assets/2160392/12025841/f2cc6ca0-ad99-11e5-9f04-cf7368f64d75.png)

**Comment by andersoonweb** [comment]
Aeeê!! Qualquer bugix comunica aqui!
