### ISSUE TITLE
Menu de categorias não abre em mobile

### ISSUE THREAD

**Issue by luisfmsouza** [free-time/free-time.github.io#66]
O menu de categorias não expande pra mostrar as categorias em mobile devices.

Esse screeshot foi de um iPhone 6, usando o Safari.

![img_3391](https://cloud.githubusercontent.com/assets/4405147/11975035/da8ef088-a950-11e5-8460-c784ef4e605b.PNG)

**Comment by andersoonweb** [comment]
Parou de funcionar até no meu android aqui...

**Comment by luisfmsouza** [comment]
Debugando rapidão, notei que o evento de click(abaixo) é aplicado duas vezes:

```
$(".nav-category").click(function() {
    $(".sub-menu").toggle()
});
```

Você tem alguma ideia do que pode ser? Senão, eu posso investigar melhor depois.

**Comment by andersoonweb** [comment]
@luisfmsouza não, um PR que aceitei sem muito cuidado foi uma melhoria desse lance ai, vamos debugar e partilhar a melhor solução aqui ? :dancer:

**Comment by femontanha** [comment]
@andersonweb o meu PR https://github.com/free-time/free-time.github.io/pull/64 arrume esse problema

**Comment by andersoonweb** [comment]
@femontanha perdão, não tinha visto! =)

**Comment by femontanha** [comment]
@andersonweb My PR was merged, but the menu problem still not working because it depends of Inphinity library. I opened a PR for this:  https://github.com/raphamorim/inphinity/pull/12

@raphamorim repository :)

**Comment by andersoonweb** [comment]
Nice @femontanha :dancer:

**Comment by andersonweb** [comment]
#42d57a6
