### ISSUE TITLE
algumas urls dos videos estão erradas

### ISSUE THREAD

**Issue by walternascimentobarroso** [free-time/free-time.github.io#73]
em um dos ultimos links de videos(tou assistindo de baixo para cima :D ), o video do Fábio Ricotta SEO para Front-end, nao é exibido, quando clika no link abre a palestra do Renzo Nuccitelli

**Comment by walternascimentobarroso** [comment]
a palestra do Luciano Ramalho JavaScript com Google V8 no servidor, tambem esta com o mesmo error

**Comment by fdaciuk** [comment]
@walternascimentobarroso, pode enviar um pull request com as correções, por favor?

**Comment by andersoonweb** [comment]
Eu tinha feito mais cedo, só tinha esquecido de mandar o PR. #79 

Obrigado por alertar @walternascimentobarroso ! Se achar novos erros, abre um issue e manda um PR. Abração!
