### ISSUE TITLE
[Bug] Assinando o feed de news no rodapé.

### ISSUE THREAD

**Issue by cristofersousa** [free-time/free-time.github.io#75]
Quando você vai inserir seu e-mail para assinar a feed de news no rodapé tem o campo para inserir o e-mail após fazer isso ele redireciona você para outra page e pede para inserir o e-mail novamente. 
Acho que se o form do rodapé não estiver pegando o input pode colocar uma _blank para o usuário fazer isso assim fica mais transparente esse processo e não faz ele digitar 2x.

**Comment by andersoonweb** [comment]
@cristofersousa nosso amigo @fdaciuk já está resolvendo isso. #44 
Obrigado pela dica.

**Comment by fdaciuk** [comment]
Done!
