### ISSUE TITLE
Integração com o Speakerfight

### ISSUE THREAD

**Issue by luanfonceca** [free-time/free-time.github.io#76]
Fala galera, eu sou o fundador do http://github.com/luanfonceca/speakerfight e lá nós temos uma página para o perfil do pessoal: http://speakerfight.com/profile/luanfonceca/ seria interesante se eu pudesse mostrar outras palestras que aquele cara já fez, vocês acham que teríamos como fazer uma integração dessas?

**Comment by andersoonweb** [comment]
Opa @luanfonceca ! Cara, confesso que já tive essa ideia, melhor, eu tentei fazer, mas não tive muito exceto e deixei pra depois, sabe aquele dia cansativo que você tem e quer deixar tudo pra  outra hora, foi isso que ocorreu... 

Então, me conte como podemos ou quais suas ideias pra fazer essa interação, a ideia é muito válida, curtir bastante e parabéns pelo projeto.

Conto com você pra implementarmos essa nova feature sensacional.

**Comment by luanfonceca** [comment]
Show boy, o que eu imagino é oq: Isso iria virar um link pra uma página de perfil.
![screen shot 2016-01-14 at 3 17 30 am](https://cloud.githubusercontent.com/assets/1490875/12317183/751391cc-ba6d-11e5-9b66-cde3d926f00e.png)

Quando eu fui fazer a do speakerfight eu baixei naquele bootsnipp um layout de profile. KKKKKKK
Mas um que eu acho que fica legal no teu caso é o do speakerdeck: https://speakerdeck.com/luanfonceca/ onde tem os vídeozinhos epanz.

## 

Pra mim, o mais simples pra funcionar é uma api ou um embedded pra colocar no profile.
![screen shot 2016-01-14 at 3 22 43 am](https://cloud.githubusercontent.com/assets/1490875/12317245/1d7fcb64-ba6e-11e5-9823-10900f9cd57d.png)

**Comment by andersoonweb** [comment]
Era exatamente o que eu estava pensando. Bom, pesquisando por soluções, poderia fazer algo como [isso](http://jekyllrb.com/docs/datafiles/). Acho que encaixaria muito bem e melhor, é "nativo" do Jekyll. 

PS: é o mesmo lance que fazemos para as categorias.
