### ISSUE TITLE
Lazy Loading

### ISSUE THREAD

**Issue by willianjusten** [free-time/free-time.github.io#9]
Implementar lazy loading nas imagens. Como vemos no gráfico, mesmo com as melhorias, as imagens são o gargalo do projeto. O lazy loading vai ajudar a carregar as imagens por demanda e agilizar para o usuário =)

![screen shot 2015-06-07 at 09 40 37](https://cloud.githubusercontent.com/assets/3991845/8024223/71256af4-0d02-11e5-880f-b42bef46d36d.png)

**Comment by andersoonweb** [comment]
Implementado @willianjusten ! Excelente pratica, ajudou bastante com a performance do projeto.

Segue o gráfico atual:

![teste](https://cloud.githubusercontent.com/assets/3930770/8145749/4c379bca-11eb-11e5-99d8-08a09ab81136.png)

Ainda não implementei nenhum load. Queria saber de você se é necessário usar um imagem ou podemos fazer um load em css e implementar ele com Javascript puro, jQuery ou outra tecnologia. Não sei como funciona esse processo, mas é possível ? Nesse caso teria que fazer a chamada pra o do load para dentro do <code>src=""</code>.

cc: @Lucaslimay @willianjusten @rafaelstz

**Comment by willianjusten** [comment]
Achei meio estranho o gráfico...Aparentemente o número de imagens diminuiu drasticamente (o que é bom e foi a intenção), mas o tamanho ficou quase o mesmo que loadando tudo...

Não olhei a implementação ainda, mas achei bem estranho...

**Comment by andersoonweb** [comment]
bom, implementei como segue o site oficial. Apenas removi uma linha de código que foi essa: 
<code>
callback: function (element, op) {
      console.log(element, 'has been', op + 'ed')
    }
</code>
Pelo que sei, essa linhar retornava no console quando a imagem era retornada. Enfim, quando puder dá uma olhadinha na implementação. Mais de qualquer forma, ficou menor um pouco.

**Comment by willianjusten** [comment]
Já olhei aqui, fizemos umas alterações e agora já está de acordo e tudo funcionando. =)
