### ISSUE TITLE
Video Data Binding Revolution

### ISSUE THREAD

**Issue by walternascimentobarroso** [free-time/free-time.github.io#92]
no free time, aparece que o nome do vídeo é "Data Binding Revolution"
palestrada por Por: "Ricardo Cabello"

mas quando abre a URL é essa https://www.youtube.com/watch?v=vjNQLuTEWb4
e abri um vídeo bloqueado por direitos autorais (na verdade não abre o vídeo :D ) 

pesquisando achei apenas uma entrevista por Ricardo Cabello(https://www.youtube.com/watch?v=iETFCdQlYrg), mas não achei palestra nenhuma

agora a duvida, qual vídeo era para estar lá? eu iria mandar uma correção com o link certo mas não sei qual é o certo :D

**Comment by luisfmsouza** [comment]
Vi que tá no canal da BrazilJS no Youtube, vou perguntar no slack pro pessoal que administra o canal.

Vamos ver...

**Comment by walternascimentobarroso** [comment]
blz ;)

**Comment by luisfmsouza** [comment]
@walternascimentobarroso liberaram o vídeo, mas acho que tá sem áudio :(

Testa ai, se tiver sem áudio mesmo, talvez seja melhor remover. O que acha @andersonweb ?

**Comment by walternascimentobarroso** [comment]
Realmente esta sem áudio

**Comment by andersoonweb** [comment]
Realmente está sem áudio. @luisfmsouza 

Vou tentar um contato uns dos organizadores do evento, dependendo da posição que ele me dê, deletamos. O que acham?

**Comment by luisfmsouza** [comment]
Combinado @andersonweb !

**Comment by walternascimentobarroso** [comment]
concordo ;) @andersonweb

**Comment by andersoonweb** [comment]
Bom, falei com ele há três dias. Não me respondeu. Provavelmente deve estar ocupado ou férias, vai saber. O melhor é deletar e se um dia normalizar ou ele me responder reupamos! Tudo bem?

**Comment by luisfmsouza** [comment]
Combinado!

Att,

_Luís Felipe Souza_

Em 1 de fevereiro de 2016 20:47, Anderson Menezes notifications@github.com
escreveu:

**Comment by andersoonweb** [comment]
Tranquilo pra você @walternascimentobarroso ? :)

**Comment by walternascimentobarroso** [comment]
blz @andersonweb 
:D
